### ISSUE TITLE
如果更新数据，怎么标记使[RedisCache]的方法能更新到最新更新的数据

### ISSUE THREAD

**Issue by liuyl1992** [VictorTzeng/Zxw.Framework.NetCore#11]
如果更新数据，怎么标记使[RedisCache]的方法能更新到最新更新的数据：
更新数据，标记[RedisCache]的方法查询到的是缓存老数据吗，更新redis的机制暂时需要自己主动更新吗

**Comment by VictorTzeng** [comment]
需要在程序里实现清除缓存的功能。
