### ISSUE TITLE
IBaseModel在意义上的话抽象类会更好吧

### ISSUE THREAD

**Issue by liuyl1992** [VictorTzeng/Zxw.Framework.NetCore#13]
IBaseModel在意义上的话抽象类会更好吧，大部分框架也都这样设计，抽象类中放Id也更贴切，还有就是IBaseModel中你没有控制并发情况的出现，所以里面加 [Timestamp]标记的一列字节类型并发处理会更好，还有基本的创建时间，更新时间，状态这都是每条数据都应该有的

 /// <summary>
        /// DB 資料版號
        /// </summary>
        [Timestamp]
        public byte[] RowVersion { get; set; }

**Comment by VictorTzeng** [comment]
[Timestamp]这个特性我测试了一下，在pg数据库里不好使

**Comment by liuyl1992** [comment]
在mysql也不好使，但是ConcurrencyCheck这个特性是可以的，但是就要手动更新指定字段了

**Comment by VictorTzeng** [comment]
@liuyl1992 有CQRS实践Demo推荐吗？
