### ISSUE TITLE
DbContext的生命周期问题

### ISSUE THREAD

**Issue by LambertW** [VictorTzeng/Zxw.Framework.NetCore#14]
Dev分支中，使用的是**AddSingleton<T>()**方式，不合适。
应该使用**AddScoped**进行注入。

**Comment by LambertW** [comment]
至于使用了Scoped方式后，EntityFrameworkCore.Triggers中报错问题，
请尝试使用
```c#
Triggers<SysMenu>.Updating += entry =>
            {
                var parentMenu = entry.Context.Set<SysMenu>().Find(entry.Entity.ParentId);
                entry.Entity.SortIndex = entry.Entity.Id;
                entry.Entity.MenuPath = (parentMenu?.MenuPath ?? "0") + "," + entry.Entity.Id;
            };
```

**Comment by VictorTzeng** [comment]
谢谢指正。在项目里，DbContext和Repository的生命周期都由DI控制。DbContext的生命周期我是参照AddDbContext来的，源码里是用的AddSingleton。我刚刚测试了一下，改为Scoped后会报错，提示无法访问已释放过的资源。改为Singleton和Transient都没问题。

**Comment by LambertW** [comment]
> 谢谢指正。在项目里，DbContext和Repository的生命周期都由DI控制。DbContext的生命周期我是参照AddDbContext来的，源码里是用的AddSingleton。我刚刚测试了一下，改为Scoped后会报错，提示无法访问已释放过的资源。改为Singleton和Transient都没问题。

我已经测试过了，此问题是由Triggers引起，解决方式也在以上列出。
```c#
entry.Context.Set<SysMenu>().Find(entry.Entity.ParentId);
```

**Comment by VictorTzeng** [comment]
我已经修改了和更新了nuget，并将demo分离出来新建了一个[repository](https://github.com/VictorTzeng/Zxw.Framework.NetCore.Demo)。万分感谢指正~~ @LambertW
