### ISSUE TITLE
Microsoft.EntityFrameworkCore包升级成2.1.0版本后会报异常

### ISSUE THREAD

**Issue by ggh5270** [VictorTzeng/Zxw.Framework.NetCore#17]
将demo的nuget包全部升级，即Microsoft.EntityFrameworkCore包版本为2.1.0，会报Method not found: 'Void Microsoft.EntityFrameworkCore.Storage.Internal.RelationalParameterBuilder..ctor(Microsoft.EntityFrameworkCore.Storage.IRelationalTypeMapper)'.)|InnerException:Method not found: 'Void Microsoft.EntityFrameworkCore.Storage.Internal.RelationalParameterBuilder..ctor(Microsoft.EntityFrameworkCore.Storage.IRelationalTypeMapper)'这个异常，降级为2.0.3才正常。请问楼主有没这问题？

**Comment by VictorTzeng** [comment]
你重新拉一下代码，我更新了nuget包。

**Comment by ggh5270** [comment]
重新拉代码了，的确是会报异常

![1528717474 1](https://user-images.githubusercontent.com/12028229/41229840-1a30d276-6db0-11e8-9225-13e354c2f68f.png)

**Comment by VictorTzeng** [comment]
你是怎么操作的？目前文档还没完善，刚开始需要执行在SYSUser表内置一条数据，然后需要执行Home/Init，初始化菜单模块。最后再进入系统。

**Comment by ggh5270** [comment]
跟数据的初始化没关，我是在demo里另外建了一个方法，数据库用的是mysql，执行操作数据库的地方就会报这个错，难道跟mysql有关？

**Comment by VictorTzeng** [comment]
是由于所用到的MySQL驱动包还未支持2.1版本，你可以换成预览版试试
