### ISSUE TITLE
NET CORE 2.1 错误 无法运行

### ISSUE THREAD

**Issue by JosonJiang** [VictorTzeng/Zxw.Framework.NetCore#19]
`An unhandled exception occurred while processing the request.

InvalidOperationException: The property expression 'm => Convert(m.Id, Object)' is not valid. The expression should represent a property access: 't => t.MyProperty'. For more information on including related data, see http://go.microsoft.com/fwlink/?LinkID=746393.

Microsoft.EntityFrameworkCore.Query.ResultOperators.Internal.IncludeExpressionNode.CreateResultOperator(ClauseGenerationContext clauseGenerationContext)`

**Comment by JosonJiang** [comment]
换mySQL 和 SQL server 都不行

**Comment by JosonJiang** [comment]
![0](https://user-images.githubusercontent.com/3362073/41335697-48aa2c8e-6f1c-11e8-94ed-68e3b4311249.png)
![9](https://user-images.githubusercontent.com/3362073/41335708-50ad71c0-6f1c-11e8-8ff3-8ff43141bb63.png)

**Comment by VictorTzeng** [comment]
麻烦提供一下出现异常的具体代码段

**Comment by VictorTzeng** [comment]
你这应该master分支吧？最新代码请下载dev分支

**Comment by JosonJiang** [comment]
Zxw.Framework.Website 下面的web 程序(⊙o⊙)…

```
      public IActionResult Index()
        {
            // CodeGenerator.Generate();//生成所有实体类对应的Repository和Service层代码文件
            // CodeGenerator.GenerateSingle<TutorClassType, int>();//生成单个实体类对应的Repository和Service层代码文件
            var list = iTutorClassTypeService.Get(m => true, m => m.Id, m => m.Active);
            return View(list);
        }

```

调用的

```
 public virtual IQueryable<T> Get(Expression<Func<T, bool>> @where = null, params Expression<Func<T, object>>[] includes)
 {
            if (includes == null)
                return Get(where);
            var query = _set.AsQueryable();
            foreach (var include in includes)
            {
                query = query.Include(include);
            }



           //  return @where != null ? query.Where(@where) : query;

           return  @where != null ? query.AsNoTracking().Where(@where) : query.AsNoTracking();
        }
```

我改成注释那里也不行

**Comment by JosonJiang** [comment]
dev 下面都没有一个demo ，下载下来 单元测试也是空的 不玩了 O(∩_∩)O哈哈~

**Comment by VictorTzeng** [comment]
https://github.com/VictorTzeng/Zxw.Framework.NetCore.Demo 这是demo，dev里面分出来了，单元测试尚未提交
