### ISSUE TITLE
不知道你这边怎么处理ef core的多对多关系？

### ISSUE THREAD

**Issue by zhanfu86** [VictorTzeng/Zxw.Framework.NetCore#2]
看过你代码中的dbcontext 部分，通过反射来获取所有model（不依赖model），使用的是data annotations。但ef core的多对多关系必须使用 Fluent API，不知道你怎么处理的，还请指教。

**Comment by VictorTzeng** [comment]
你可以先看看官方文档：https://docs.microsoft.com/en-us/ef/core/modeling/relationships
