### ISSUE TITLE
Zxw.Framework.Pay

### ISSUE THREAD

**Issue by Varorbc** [VictorTzeng/Zxw.Framework.NetCore#20]
https://github.com/VictorTzeng/Zxw.Framework.NetCore/blob/429be7acf9c4e32bded7cc9548475394520e5d9e/Zxw.Framework.Pay/Zxw.Framework.Pay.csproj#L8
已经更新为[PaySharp](https://github.com/Varorbc/PaySharp)

**Comment by VictorTzeng** [comment]
ok，谢谢作者大佬不远万里跋山涉水来通知😘

**Comment by Varorbc** [comment]
@VictorTzeng 在github上突然看到，就来告诉你一声了，

**Comment by VictorTzeng** [comment]
大概看了下，好像是重构，改动比较大...

**Comment by Varorbc** [comment]
是的，之前局限太大了
