### ISSUE TITLE
Reload enity

### ISSUE THREAD

**Issue by Diaskhan** [VictorTzeng/Zxw.Framework.NetCore#26]
How do U reload Enity configutation or entity? 

when new property is added ? (field of entity)

**Comment by VictorTzeng** [comment]
@Diaskhan In the development environment, I usually drop the database directly. In the formal environment, you can manually change the data table and entity at the same time, if the changes are not much. Of course, you can also use the database migration command.

**Comment by Diaskhan** [comment]
not Victor i actually talking about another thing

1.We could create tablewith fields
2.then could make entitytypeconfiguration https://stackoverflow.com/questions/26957519/ef-core-mapping-entitytypeconfiguration
3.Generate class model

4.Compile it in assembly
5.Load assembly to memory and use in dbcontext.SET<>

The problem gets when we want recompile class and reload a newer version of entitclass!

**Comment by VictorTzeng** [comment]
Sorry, Diaskhan, I have not encountered this situation yet. Could you show me your codes or exceptions?

**Comment by Diaskhan** [comment]
no it problem of net core !
https://github.com/dotnet/coreclr/issues/552
