### ISSUE TITLE
RedisCacheAttribute 拦截好像在demo也没有实现

### ISSUE THREAD

**Issue by ghd258** [VictorTzeng/Zxw.Framework.NetCore#28]
RedisCacheAttribute 拦截好像在demo也没有实现  应该是返回的类型有问题  有好的实现方法吗

**Comment by VictorTzeng** [comment]
是有的，不过在仓储接口层
![image](https://user-images.githubusercontent.com/7413525/45912063-5524c600-be4e-11e8-9b39-e3c0298dede8.png)

**Comment by ghd258** [comment]
这个返回值应该有问题

**Comment by ghd258** [comment]
界面上没有调用这个

**Comment by VictorTzeng** [comment]
......建议你打断点一步步调试就会明白的
