### ISSUE TITLE
这个项目能实现Code First吗

### ISSUE THREAD

**Issue by quezhihui** [VictorTzeng/Zxw.Framework.NetCore#29]
No DbContext was found in assembly 'Zxw.Framework.Website.Models'. Ensure that you're using the correct assembly and that the type is neither abstract nor generic.

使用Add-Migration 命令报错

**Comment by VictorTzeng** [comment]
本项目本身就是基于efcore code first的，你可以介绍下你的思路和流程，如何遇到这个问题

**Comment by quezhihui** [comment]
这个问题解决了，忘了回复，需要在service注入的时候加上services.AddDbContext
