### ISSUE TITLE
如何处理并发锁的问题

### ISSUE THREAD

**Issue by ggh5270** [VictorTzeng/Zxw.Framework.NetCore#30]
多用户操作同一条数据，请问有什么好的方法处理这种并发问题？

**Comment by VictorTzeng** [comment]
园子里顾总大佬有篇文章写了关于efcore并发的解决方案

**Comment by VictorTzeng** [comment]
https://www.cnblogs.com/GuZhenYin/p/7761352.html 你参考一下

**Comment by ggh5270** [comment]
这有看过，觉得里面介绍的是处理特定字段的并发，这样写法那需要处理好多字段才行，有没有一种可以自动处理所有字段的写法参考？ @VictorTzeng
