### ISSUE TITLE
关于Cache Attribute，现在代码里只有 Set Key 行为， 有没有Remove对应的attribute吗

### ISSUE THREAD

**Issue by xuyae573** [VictorTzeng/Zxw.Framework.NetCore#34]
关于Cache Attribute，现在代码里只有 Set Key 行为， 有没有Remove对应的attribute吗

**Comment by VictorTzeng** [comment]
有的，在这里https://github.com/VictorTzeng/Zxw.Framework.NetCore/blob/master/Zxw.Framework.NetCore/Cache/DistributedCacheManager.cs
