### ISSUE TITLE
请更新下Blueshift.EntityFrameworkCore.MongoDB的包源

### ISSUE THREAD

**Issue by wannvmi** [VictorTzeng/Zxw.Framework.NetCore#38]
Blueshift.EntityFrameworkCore.MongoDB-preview 已经过期 ，
现在 要使用Version 2.2.0-rtm-1
```shell
Install-Package Blueshift.EntityFrameworkCore.MongoDB-aleksamagicka -Version 2.2.0-rtm-1
```
不更新无法生成项目

**Comment by wannvmi** [comment]
[nuget 下载地址](https://www.nuget.org/packages/Blueshift.EntityFrameworkCore.MongoDB-aleksamagicka/2.2.0-rtm-1)

**Comment by VictorTzeng** [comment]
好的。Blueshift.EntityFrameworkCore.MongoDB的包源之前只存在在[myget](https://www.myget.org/gallery/efcore-mongodb/)上

**Comment by VictorTzeng** [comment]
@wannvmi 已更新，请拉取最新代码
