### ISSUE TITLE
首次运行错误,数据库mssql,求解一下

### ISSUE THREAD

**Issue by sinokiwa** [VictorTzeng/Zxw.Framework.NetCore#4]
An unhandled exception occurred while processing the request.
InvalidOperationException: The property expression 'm => Convert(m.Id, Object)' is not valid. The expression should represent a property access: 't => t.MyProperty'. For more information on including related data, see http://go.microsoft.com/fwlink/?LinkID=746393.

**Comment by VictorTzeng** [comment]
做修改没有？

**Comment by sinokiwa** [comment]
没有修改，只把数据库改到MSSQL
Startup.cs
82: var connectionString = Configuration.GetConnectionString("MsSqlServer");
87: DbType = DbType.MSSQLSERVER
appsettings.json
9:    "MsSqlServer": "Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=HolidaySchool;Integrated Security=True;Pooling=False",
这里数据库实例为SqlServer2016LocalDB（2017自带的）

**Comment by sinokiwa** [comment]
执行query.include(include)

**Comment by VictorTzeng** [comment]
请问你用的哪个分支呢？

**Comment by sinokiwa** [comment]
@VictorTzeng 直接下载的zip

**Comment by VictorTzeng** [comment]
呃，建议用dev分支。我目前还在休假，你先自行研究一下。欢迎提交pr
