### ISSUE TITLE
AddCoreX这个方法,怎么保证实例化顺序

### ISSUE THREAD

**Issue by coolxiaomi** [VictorTzeng/Zxw.Framework.NetCore#43]
AddCoreX这个方法怎么保证DbContext->Repository->UnitOfWork->Service->api,因为构造函数中彼此有顺序,所以我用这个方法一直没有成功,望指教.
此外Core3.1 中AspectCoreContainer.BuildServiceProvider方法中一直不成功.也请指教是否是用法有问题.
框架很不错,思想也很赞,非常感谢!

**Comment by VictorTzeng** [comment]
https://github.com/VictorTzeng/Zxw.Framework.NetCore.Demo/blob/master/src/Zxw.Framework.Website/Startup.cs 可以参考一下这个。欢迎一起学习交流~
