### ISSUE TITLE
支持存储过程吗

### ISSUE THREAD

**Issue by dzvane** [VictorTzeng/Zxw.Framework.NetCore#45]
支持存储过程吗，存储过程怎么调用

**Comment by VictorTzeng** [comment]
按理说是可以的。如果是存储过程返回的是DataTable，封装了[SqlQuery](https://github.com/VictorTzeng/Zxw.Framework.NetCore/blob/7988f3d05c8c6064d4dc10fe4f3552e882b195f0/Zxw.Framework.NetCore/DbContextCore/BaseDbContext.cs#L363)，你需要定义输出DataTable对应的实体类；
如果只是单纯的执行存储过程，调用[ExecuteSqlWithNonQuery](https://github.com/VictorTzeng/Zxw.Framework.NetCore/blob/7988f3d05c8c6064d4dc10fe4f3552e882b195f0/Zxw.Framework.NetCore/DbContextCore/BaseDbContext.cs#L166)即可

**Comment by dzvane** [comment]
好的谢谢大大
