### ISSUE TITLE
我想加个Service层怎么处理呢？

### ISSUE THREAD

**Issue by ly12530** [VictorTzeng/Zxw.Framework.NetCore#46]
我想加个Service层怎么处理呢？业务逻辑放在这里面处理。还有就是注入的时候  可以使用命名空间不使用dll文件名来注入吗

**Comment by VictorTzeng** [comment]
继承一下[BaseService](https://github.com/VictorTzeng/Zxw.Framework.NetCore/blob/master/Zxw.Framework.NetCore/Services/BaseService.cs)；
按Namespace注入后面加上哈

**Comment by ly12530** [comment]
好的

**Comment by ly12530** [comment]
顺便问一下呢  

InvalidOperationException: Unable to activate type 'DH.Core.DbContextCore.MySqlDbContext'. The following constructors are ambiguous:
Void .ctor(Microsoft.Extensions.Options.IOptions`1[DH.Core.Options.DbContextOption])
Void .ctor(Microsoft.EntityFrameworkCore.DbContextOptions)

这个问题你知道怎么解决么 ？还是注入的时候有问题 ，我按照demo里面注入的

**Comment by VictorTzeng** [comment]
https://github.com/VictorTzeng/Zxw.Framework.NetCore/blob/7988f3d05c8c6064d4dc10fe4f3552e882b195f0/Zxw.Framework.NetCore/DbContextCore/MySqlDbContext.cs#L28 把这一行注释掉

**Comment by ly12530** [comment]
```
 public MySqlDbContext(IOptions<DbContextOption> option) : base(option)
        {
        }

        public MySqlDbContext(DbContextOptions options) : base(options){}
```
两个都注释了可以了

出了个新问题  service层在web层调用不了  我已经注入了 

System.AggregateException
  HResult=0x80131500
  Message=Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: DH.Web.Controllers.HomeController Lifetime: Transient ImplementationType: DH.Web.Controllers.HomeController': Unable to resolve service for type 'DH.Service.UserService' while attempting to activate 'DH.Web.Controllers.HomeController'.) (Error while validating the service descriptor 'ServiceType: Microsoft.Extensions.DependencyInjection.ISupportRequiredService Lifetime: Scoped ImplementationType: AspectCore.Extensions.DependencyInjection.SupportRequiredService': Unable to resolve service for type 'AspectCore.DependencyInjection.IServiceResolver' while attempting to activate 'AspectCore.Extensions.DependencyInjection.SupportRequiredService'.) (Error while validating the service descriptor 'ServiceType: Microsoft.Extensions.DependencyInjection.IServiceScopeFactory Lifetime: Scoped ImplementationType: AspectCore.Extensions.DependencyInjection.ServiceScopeFactory': Unable to resolve service for type 'AspectCore.DependencyInjection.IServiceResolver' while attempting to activate 'AspectCore.Extensions.DependencyInjection.ServiceScopeFactory'.)
  Source=Microsoft.Extensions.DependencyInjection
  StackTrace:
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at DH.Web.Program.Main(String[] args) in E:\workspace\luoyong\project\DH\DH.Web\Program.cs:line 16

  此异常最初是在此调用堆栈中引发的: 
    [外部代码]

内部异常 1:
InvalidOperationException: Error while validating the service descriptor 'ServiceType: DH.Web.Controllers.HomeController Lifetime: Transient ImplementationType: DH.Web.Controllers.HomeController': Unable to resolve service for type 'DH.Service.UserService' while attempting to activate 'DH.Web.Controllers.HomeController'.

内部异常 2:
InvalidOperationException: Unable to resolve service for type 'DH.Service.UserService' while attempting to activate 'DH.Web.Controllers.HomeController'.

**Comment by VictorTzeng** [comment]
IService接口定义了吗

**Comment by ly12530** [comment]
解决了  代码写错了 

问题又来了......... 帮忙看一下  谢谢
InvalidOperationException: Unable to resolve service for type 'AspectCore.DependencyInjection.IServiceResolver' while attempting to activate 'AspectCore.Extensions.DependencyInjection.SupportRequiredService'.

**Comment by VictorTzeng** [comment]
这个需要看你的源代码了，报错的具体地方

**Comment by ly12530** [comment]
加你QQ了 我发你 帮我看看 谢谢
