### ISSUE TITLE
能否增加Redis以及MemoryCache的开关啊？

### ISSUE THREAD

**Issue by yilezhu** [VictorTzeng/Zxw.Framework.NetCore#8]
能否增加Redis以及MemoryCache的开关啊？再配置文件或者其他常量中能够进行配置这样是否更好？
还有就是现在已经取消了 Services 以及 Services了吗？能否添加REST webapi框架啊？

**Comment by VictorTzeng** [comment]
1.能否增加Redis以及MemoryCache的开关啊？------这是Attribute，不用直接从接口方法上去掉就OK
2.还有就是现在已经取消了 Services 以及 Services了吗？ -------个人感觉Services只是多一层封装而已，代码量就多了，Repository就够了
3.能否添加REST webapi框架啊？ ------ 正在计划之中


感谢使用，也非常欢迎和感谢提各种意见以及pull request~~
